# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emojiterm < Formula
  desc ""
  homepage "https://github.com/wunderkind2k1/emojiterm"
  version "0.0.1"

  on_macos do
    url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.1/emojiterm_0.0.1_Darwin_all.tar.gz"
    sha256 "531dfb91f6e96c2a9213370e6ab23a3790b2ea41d9b3ed32ea56f3890df4ba8c"

    def install
      bin.install "emojiterm"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.1/emojiterm_0.0.1_Linux_armv6.tar.gz"
      sha256 "47f56bd455124a06488f476636d25bec4a46bd74ea65d79fc48e156ecbebab6a"

      def install
        bin.install "emojiterm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.1/emojiterm_0.0.1_Linux_x86_64.tar.gz"
      sha256 "225a7711a0f441ee53c738eb5209625d158cbbb3b6e547e54cdc21d315d006da"

      def install
        bin.install "emojiterm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.1/emojiterm_0.0.1_Linux_arm64.tar.gz"
      sha256 "7c64783d7165636e6a28c8d3c6198fde053d0236400cd97992c60469c654c40d"

      def install
        bin.install "emojiterm"
      end
    end
  end
end
