# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emojiterm < Formula
  desc ""
  homepage "https://github.com/wunderkind2k1/emojiterm"
  version "0.0.2"

  on_macos do
    url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.2/emojiterm_0.0.2_Darwin_all.tar.gz"
    sha256 "46c05635477ade5cdd910a88daa6e6e5a448bd8e9d53f31d506fd65e3fce77ed"

    def install
      bin.install "emojiterm"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.2/emojiterm_0.0.2_Linux_x86_64.tar.gz"
      sha256 "7ec2f211cc5a00f16787fef8d20d0007f2cc53de064836ca06287960f9bc75a9"

      def install
        bin.install "emojiterm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.2/emojiterm_0.0.2_Linux_armv6.tar.gz"
      sha256 "eea0b6c14747e492d5a106b8f8da979aa99d6bf660d7af54cf183a07dc507446"

      def install
        bin.install "emojiterm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wunderkind2k1/emojiterm/releases/download/v0.0.2/emojiterm_0.0.2_Linux_arm64.tar.gz"
      sha256 "831b641f1bbdd42491aaca3cd1cab3fb62b3595776762a740e8794f65bd1de5c"

      def install
        bin.install "emojiterm"
      end
    end
  end
end
